package adminPack;

import java.sql.*;
import javax.swing.JOptionPane;
public class AdminRegister extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAdmin
     */
    public AdminRegister() {
        initComponents();
        this.setTitle("Update Admin Details Window");
        this.setSize(728, 669);
        this.setBounds(300, 10, 728, 669);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        regAdminBtn = new javax.swing.JButton();
        idTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nameTxt);
        nameTxt.setBounds(120, 330, 360, 40);

        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passTxt);
        passTxt.setBounds(120, 420, 360, 40);

        regAdminBtn.setBackground(new java.awt.Color(168, 224, 224));
        regAdminBtn.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        regAdminBtn.setForeground(new java.awt.Color(0, 0, 0));
        regAdminBtn.setText("Register");
        regAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regAdminBtn);
        regAdminBtn.setBounds(500, 330, 120, 40);
        getContentPane().add(idTxt);
        idTxt.setBounds(120, 240, 360, 40);

        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 220, 50, 15);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 310, 60, 15);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 400, 60, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register form.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -20, 750, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAdminBtnActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root", "");
         if(con!=null)
           {
               String query="INSERT INTO adminlogin VALUES(?,?,?)";
               PreparedStatement pst=con.prepareStatement(query);
               int id = Integer.parseInt(idTxt.getText().trim()); 
               pst.setInt(1,id);
               pst.setString(2, nameTxt.getText().trim());
               pst.setString(3,new String(passTxt.getPassword()));
//               String pass = new String(passTxt.getPassword());
               int count=pst.executeUpdate();
               if(count>0)
               { JOptionPane.showMessageDialog(this,nameTxt.getText()+" is added as admin");}
               else{
                   JOptionPane.showMessageDialog(this, "failed to promote "+nameTxt.getText()+" as Admin:(" );
               }
           }
        con.close();
        
        } catch (Exception e) {
        }
        JOptionPane.showMessageDialog(this, "Admin Registered Successfully");
 
            this.setVisible(false);
    }//GEN-LAST:event_regAdminBtnActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JButton regAdminBtn;
    // End of variables declaration//GEN-END:variables
}
